# Config file for RandomItem by LDX;

# Interval in minutes to give a random item;
Interval: 10

# List of random items for the plugin to choose from; Format: ID:Damage:Amount
Items:
- "295:0:1"
- "458:0:1"
- "364:0:1"
- "265:0:1"
- "391:0:1"
- "392:0:1"
- "360:0:1"
- "263:0:1"
- "6:0:1"
- "297:0:1"
- "352:0:1"
- "35:0:1"